name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android App
        uses: pwa-builder/pwa-publish@v1
        with:
          url: "https://github.io"
          android: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Code-APK
          path: ./*.apk
