
name: Build Android App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build APK from URL
        uses: swantzter/render-to-apk@v1.1
        with:
          # رابط موقعك على GitHub Pages
          url:https://abc557452-bot.github.io/smart-code-dictionary/ 
          app_name: "Smart Code Dictionary"
          output_name: "smart-code.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-bundle
          path: ./*.apkv
